import nodemailer from 'nodemailer';

/**
 * Send prediction results to email
 * @param {string} email - Recipient email
 * @param {object} predictionData - The prediction result data
 */
export const sendPredictionEmail = async (email, predictionData) => {
    try {
        // Configure transporter (using Gmail/SMTP as default placeholder)
        // Note: For real use, configure these in your .env file
        const transporter = nodemailer.createTransport({
            host: process.env.SMTP_HOST || 'smtp.ethereal.email',
            port: process.env.SMTP_PORT || 587,
            secure: false, // true for 465, false for other ports
            auth: {
                user: process.env.SMTP_USER || 'test-user@ethereal.email',
                pass: process.env.SMTP_PASS || 'test-password',
            },
        });

        // If using test account (default), let's create one dynamically for the first run if none provided
        if (!process.env.SMTP_USER && transporter.options.host === 'smtp.ethereal.email') {
            const testAccount = await nodemailer.createTestAccount();
            transporter.options.auth.user = testAccount.user;
            transporter.options.auth.pass = testAccount.pass;
        }

        // Generate email content (HTML template)
        const htmlContent = `
            <!DOCTYPE html>
            <html>
            <head>
                <style>
                    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }
                    .container { max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px; }
                    .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #5d5fef; padding-bottom: 15px; }
                    .header h1 { color: #5d5fef; margin: 0; }
                    .summary { background: #f8fafc; padding: 15px; border-radius: 6px; margin-bottom: 25px; }
                    .college-card { border: 1px solid #cbd5e1; border-radius: 8px; padding: 15px; margin-bottom: 15px; }
                    .college-name { font-size: 18px; font-weight: bold; color: #1e293b; margin-bottom: 5px; }
                    .college-meta { font-size: 14px; color: #64748b; margin-bottom: 10px; }
                    .cutoff-info { display: flex; justify-content: space-between; margin-top: 10px; border-top: 1px dashed #e2e8f0; pt: 5px; }
                    .probability { display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 12px; font-weight: 600; }
                    .prob-high { background: #dcfce7; color: #15803d; }
                    .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #94a3b8; }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>Counselling Assistant</h1>
                        <p>Your Predicted College Report</p>
                    </div>
                    
                    <div class="summary">
                        <h3>Prediction Summary</h3>
                        <p><strong>Exam Type:</strong> ${predictionData.predictionParams?.examType || 'N/A'}</p>
                        <p><strong>Rank:</strong> ${predictionData.predictionParams?.rank || 'N/A'}</p>
                        <p><strong>Category:</strong> ${predictionData.predictionParams?.category || 'N/A'}</p>
                    </div>

                    <div class="results">
                        <h3>Top College Recommendations</h3>
                        ${predictionData.predictions.slice(0, 5).map(p => `
                            <div class="college-card">
                                <div class="college-name">${p.collegeName}</div>
                                <div class="college-meta">${p.branch} | ${p.district}</div>
                                <div class="cutoff-info">
                                    <span>Predicted Chance: <span class="probability prob-high">${p.admissionProbability}%</span></span>
                                    <span>Cutoff Rank: <strong>${p.cutoffRank}</strong></span>
                                </div>
                            </div>
                        `).join('')}
                    </div>

                    <div class="footer">
                        <p>This is an automated report generated by Counselling Assistant. For details, login to our platform.</p>
                        <p>© ${new Date().getFullYear()} Admission Predictor. All rights reserved.</p>
                    </div>
                </div>
            </body>
            </html>
        `;

        // Send mail
        const info = await transporter.sendMail({
            from: `"Counselling Assistant" <${process.env.SMTP_USER || 'noreply@admissionpredictor.com'}>`,
            to: email,
            subject: `Your College Prediction Report - ${predictionData.predictionParams?.examType}`,
            html: htmlContent,
        });

        console.log("Message sent: %s", info.messageId);
        if (transporter.options.host === 'smtp.ethereal.email') {
            console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));
        }

        return { success: true, messageId: info.messageId, previewUrl: nodemailer.getTestMessageUrl(info) };
    } catch (error) {
        console.error("Error sending prediction email:", error);
        throw error;
    }
};

/**
 * Send welcome email to new users
 * @param {string} email - Recipient email
 * @param {string} name - User's name
 */
export const sendWelcomeEmail = async (email, name) => {
    try {
        const transporter = nodemailer.createTransport({
            host: process.env.SMTP_HOST || 'smtp.ethereal.email',
            port: process.env.SMTP_PORT || 587,
            secure: false,
            auth: {
                user: process.env.SMTP_USER || 'test-user@ethereal.email',
                pass: process.env.SMTP_PASS || 'test-password',
            },
        });

        if (!process.env.SMTP_USER && transporter.options.host === 'smtp.ethereal.email') {
            const testAccount = await nodemailer.createTestAccount();
            transporter.options.auth.user = testAccount.user;
            transporter.options.auth.pass = testAccount.pass;
        }

        const htmlContent = `
            <!DOCTYPE html>
            <html>
            <head>
                <style>
                    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }
                    .container { max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px; }
                    .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #5d5fef; padding-bottom: 15px; }
                    .header h1 { color: #5d5fef; margin: 0; }
                    .content { padding: 15px; margin-bottom: 25px; }
                    .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #94a3b8; }
                    .cta-button { display: inline-block; padding: 12px 24px; background: #5d5fef; color: white; text-decoration: none; border-radius: 6px; font-weight: bold; margin-top: 20px; }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>Counselling Assistant</h1>
                    </div>
                    
                    <div class="content">
                        <h3>Welcome to Counselling Assistant, ${name}!</h3>
                        <p>We're thrilled to have you here. Our platform is designed to help you navigate your college admissions with confidence using advanced data-driven predictions.</p>
                        <p><strong>With your new account, you can:</strong></p>
                        <ul>
                            <li>Predict your admission chances for various engineering and medical colleges.</li>
                            <li>Save and bookmark your favorite colleges for future reference.</li>
                            <li>Compare college fees, placements, and cutoffs in a single view.</li>
                        </ul>
                        <p>Get started today by predicting your first college!</p>
                        <a href="${process.env.FRONTEND_URL || 'http://localhost:5173'}/college-prediction-engine" class="cta-button">Start Predicting Now</a>
                    </div>

                    <div class="footer">
                        <p>This is an automated message from Counselling Assistant.</p>
                        <p>© ${new Date().getFullYear()} Admission Predictor. All rights reserved.</p>
                    </div>
                </div>
            </body>
            </html>
        `;

        const info = await transporter.sendMail({
            from: `"Counselling Assistant" <${process.env.SMTP_USER || 'noreply@admissionpredictor.com'}>`,
            to: email,
            subject: `Welcome to Counselling Assistant, ${name}!`,
            html: htmlContent,
        });

        console.log("Welcome email sent: %s", info.messageId);
        return { success: true };
    } catch (error) {
        console.error("Error sending welcome email:", error);
        return { success: false };
    }
};
